### ISSUE TITLE
Get threading working on MacOS

### ISSUE THREAD

**Issue by FrankieBetanco** [COSCS340/GiftLink#13]
MacOS has trouble creating new threads using the 'threads' library.

It throws the error: 
```
2018-02-16 12:56:16.261 python[2839:259600] WebKit Threading Violation - initial use of WebKit from a secondary thread.
/anaconda3/lib/python3.6/site-packages/webview/cocoa.py:206: UninitializedDeallocWarning: leaking an uninitialized object of type WebKitHost
  self.webkit = BrowserView.WebKitHost.alloc().initWithFrame_(rect)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "gift_link.py", line 22, in launchBrowser
    webview.create_window("Login", url, width = 640, height = 640)
  File "/anaconda3/lib/python3.6/site-packages/webview/__init__.py", line 192, in create_window
    background_color, _webview_ready)
  File "/anaconda3/lib/python3.6/site-packages/webview/cocoa.py", line 437, in create_window
    browser = BrowserView(title, url, width, height, resizable, fullscreen, min_size, background_color, webview_ready)
  File "/anaconda3/lib/python3.6/site-packages/webview/cocoa.py", line 206, in __init__
    self.webkit = BrowserView.WebKitHost.alloc().initWithFrame_(rect)
objc.error: WebKitThreadingException - -[WebView initWithFrame:frameName:groupName:] was called from a secondary thread

Assertion failed: (NSViewIsCurrentlyBuildingLayerTreeForDisplay() != currentlyBuildingLayerTree), function NSViewSetCurrentlyBuildingLayerTreeForDisplay, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1561.20.106/AppKit.subproj/NSView.m, line 14480.
Illegal instruction: 4
```
It looks like it has something to do with how threads are implemented with the Cocoa libraries on Mac. 

I'm thinking I'll either get this fixed or find an alternate library that actually works on MacOS.

**Comment by FrankieBetanco** [comment]
@iige found that the webview needed to be run from the main thread, and starting a webview from a non-main thread resulted in an error.
